name: 'Build and update Release branch'
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable tar writing to system files # Fix from https://github.com/actions/toolkit/issues/946
        run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar
      - name: Restore Apt Cache
        uses: actions/cache@v4
        with:
          save-always: true
          key: ${{ github.ref_name }}-buildfiles
          path: |
            /var/cache/apt/archives/*.deb
          restore-keys: buildfiles
      - name: Restore ConTex Cache
        uses: actions/cache@v4
        with:
          save-always: true
          key: ${{ github.ref_name }}-contextcache
          path: |
            /var/lib/texmf/luatex-cache
          restore-keys: contextcache
      - name: setup
        run: sudo apt install make texlive pandoc context lua-socket
      - name: build
        run: make pdf
      - name: publish
        env:
          RELEASE_BRANCH: release
        run: |
          echo "Publishing files"
          ls output ; cat output/*.log || true
          git checkout -B ${RELEASE_BRANCH}
          git add -f 'output/*.pdf'
          git config user.email 'ci@shjorth.dk'
          git config user.name 'CI Agent'
          git commit -m "Release"
          git push -f origin ${RELEASE_BRANCH}:${RELEASE_BRANCH}
