name: 'Build and update Release branch'
on:
  push:
    branches:
      - main
jobs:
  build-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          key: ${{ github.ref_name }}-buildfiles
          path: |
            /var/cache/apt/archives
          restore-keys: buildfiles
      - name: setup
        run: sudo apt install make pandoc context
      - name: build
        run: make
      - name: publish
        run: |
          git branch -f release
          git add -f output/*.pdf
          git commit -m "Release"
          git push -f origin release:release
