name: 'Build and update Release branch'
on:
  push:
    branches:
      - main
jobs:
  build-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          save-always: true
          key: ${{ github.ref_name }}-buildfiles
          path: |
            /var/cache/apt/archives
          restore-keys: buildfiles
      - name: setup
        run: sudo apt install make texlive pandoc context lua-socket
      - name: build
        run: make pdf
      - name: publish
        run: |
          echo "Publishing files"
          ls output ; cat output/*.log || true
          git branch -f release
          git add -f 'output/*.pdf'
          git commit -m "Release"
          git push -f origin release:release
